# -*- coding: utf-8 -*-
"""bmi-calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ykH0D5XLTGQI04Sw6e9mvIftFFjO3I7y
"""

print("🌸Welcome to BMI calculator")
weight=float(input("enter your weight in kg: 💡"))
height=float(input("enter your height in meter: 💡"))
if weight<=0 or height<=0:
  print("invalid input")
else:
  bmi=weight/(height*height)
  if bmi<18.5:
    print("you are underweight")
  elif bmi>=18.5 and bmi<25:
    print("you are normal weight")
  elif bmi>=25 and bmi<30:
    print("you are overweight")
  else:
    print("you are obese!🍔")